/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JPanel;
import modelo.Enfermedad;
import util.Fecha;

/**
 *
 * @author PC
 */
public class AdicionarEnfermedad extends javax.swing.JDialog {  
    /**
     * Creates new form VentanaEmergente
     */
    public AdicionarEnfermedad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBounds(parent.getWidth()/2-this.getWidth()/2,parent.getHeight()/2-this.getHeight()/2,this.getWidth(),this.getHeight());
        setResizable(false);
        this.clickBotonAceptar=false;
        this.objEnfermedad=null;
        
        
        
    }
    
    public boolean ejecutar(){
        setVisible(true);
        return clickBotonAceptar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextField1Nombre = new javax.swing.JTextField();
        jLabelTratamiento = new javax.swing.JLabel();
        jTextFieldTratamiento = new javax.swing.JTextField();
        jLabelFecha = new javax.swing.JLabel();
        jFormattedTextFieldFecha = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonCancelar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        jButtonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setPreferredSize(new java.awt.Dimension(32767, 32767));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jPanel4.setMinimumSize(new java.awt.Dimension(700, 116));
        jPanel4.setName(""); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(32767, 32767));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jLabelNombre.setText("Nombre de la Enfermedad");
        jPanel4.add(jLabelNombre);

        jTextField1Nombre.setMaximumSize(new java.awt.Dimension(700, 50));
        jTextField1Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1NombreActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField1Nombre);

        jLabelTratamiento.setText("Tratamiento");
        jPanel4.add(jLabelTratamiento);

        jTextFieldTratamiento.setMaximumSize(new java.awt.Dimension(700, 50));
        jTextFieldTratamiento.setMinimumSize(new java.awt.Dimension(0, 24));
        jTextFieldTratamiento.setName(""); // NOI18N
        jTextFieldTratamiento.setPreferredSize(new java.awt.Dimension(5, 6));
        jPanel4.add(jTextFieldTratamiento);

        jLabelFecha.setText("Fecha");
        jPanel4.add(jLabelFecha);

        jFormattedTextFieldFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFormattedTextFieldFecha.setMaximumSize(new java.awt.Dimension(700, 50));
        jFormattedTextFieldFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldFechaActionPerformed(evt);
            }
        });
        jPanel4.add(jFormattedTextFieldFecha);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2);

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(32767, 7000));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar);
        jPanel1.add(filler1);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAceptar);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.clickBotonAceptar=false;
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        if(validarCampos()==true && objEnfermedad!=null){
            this.clickBotonAceptar = true;
        dispose();
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jFormattedTextFieldFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldFechaActionPerformed

    private void jTextField1NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1NombreActionPerformed
     
    private boolean clickBotonAceptar;
    private Enfermedad objEnfermedad;

    public Enfermedad getObjEnfermedad() {
        return objEnfermedad;
    }
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JFormattedTextField jFormattedTextFieldFecha;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTratamiento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1Nombre;
    private javax.swing.JTextField jTextFieldTratamiento;
    // End of variables declaration//GEN-END:variables

    private boolean validarCampos() {
        boolean valido = true;
        
        String nombre = jTextField1Nombre.getText();
        
        String tratamiento = jTextFieldTratamiento.getText();
        
        String [] fecha = jFormattedTextFieldFecha.getText().split("/");
        
        if(nombre.trim().length()==0 || nombre.isEmpty()==true){
            valido =false;
        }
        
        if(tratamiento.trim().length()==0 || tratamiento.isEmpty()==true){
            valido =false;
        }
        
        if(fecha.length!=3){
            valido = false;
        }
        
        if(valido){
            int dia = Integer.parseInt(fecha[0]);
            int mes = Integer.parseInt(fecha[1]);
            int anio = Integer.parseInt(fecha[2]);  
            
            Fecha fechaEnfermedad = new Fecha(dia,mes,anio);
            
            objEnfermedad = new Enfermedad(nombre,fechaEnfermedad,tratamiento);
            
            
        }
        return true;
        
    }

}